# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSNetworking' do
pod 'AFNetworking'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JSNetworking

  target 'JSNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSNetworkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
